name: CI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-kernel:
    name: Build Kernel
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Build Kernel
        run: cd a05m-kernel-6.6 && bash build_kernel.sh
      - name: Upload File to Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "../a05m-6.6-kernel.zip"  # Path to the file you want to attach as a package
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
